Timur katimullin tasks 91 100
linkouth/ui-internship-lwo2 pull request #10
Opened 2019-09-23 06:55 UTC by linkouth

Adds 91-100 tasks solutions.

2019-09-24 07:57 UTC, vovcyan requested changes

2019-09-24 07:57 UTC, vovcyan commented on tasks/91_make-a-person/make-a-person.js
> +    this.setFirstName(names[0]);
Please use ES6 features

2019-09-24 07:57 UTC, vovcyan commented on tasks/95_fat-fingers/fat-fingers.js
> +  if (str.length === 0) {
!str.length

2019-09-24 07:57 UTC, vovcyan commented on tasks/98_linked-list/linked-list.js
> +    if (this.tail === null) {
!this.tail

2019-09-24 07:57 UTC, vovcyan commented on tasks/99_stack/Stack.js
> +    if (this.last === null) {
The same

2019-09-24 07:57 UTC, vovcyan commented on tasks/99_stack/Stack.js
> +    return this.size === 0;
!!this.size

2019-09-25 11:54 UTC, akimovaa approved these changes

2019-09-25 12:08 UTC, KalachevDev commented on tasks/91_make-a-person/make-a-person.js
> +    return this.lastName;
It seem you have to implement it other way. You need to keep it as private

2019-09-25 12:09 UTC, KalachevDev commented on tasks/95_fat-fingers/fat-fingers.js
> +  return char >= 'A' && char <= 'Z';
you could use regexp here

2019-09-25 12:19 UTC, vovcyan approved these changes

2019-09-25 12:35 UTC, merged