Timur katimullin training 1 4
linkouth/ui-internship-lwo2 pull request #11
Opened 2019-09-25 11:35 UTC by linkouth

Adds training tasks 1-4 solutions.

2019-09-25 15:39 UTC, vovcyan submitted a review, later dismissed

2019-09-26 05:01 UTC, alexkond requested changes

2019-09-26 05:01 UTC, alexkond commented on training/1_populate_table/populate-table.js
> +  document.body.appendChild(table);
This is a really bad practice to append element to the DOM and mutating it after that! Please read about [repaint and reflow](http://www.phpied.com/rendering-repaint-reflowrelayout-restyle/). Doing this way you're causing the browser to recalculate the page on every node insertion.

2019-09-26 07:49 UTC, vovcyan approved these changes

2019-09-26 07:57 UTC, akimovaa approved these changes

2019-09-26 08:01 UTC, merged