Timur katimullin tasks 61 70
linkouth/ui-internship-lwo2 pull request #7
Opened 2019-09-19 15:02 UTC by linkouth

Adds solutions 61-70 tasks.

2019-09-24 07:53 UTC, vovcyan requested changes

2019-09-24 07:53 UTC, vovcyan commented on tasks/62_swap-cases/swap-cases.js
> +        char.toLowerCase() :
char.toLowerCase() : char.toUpperCase())

2019-09-24 07:53 UTC, vovcyan commented on tasks/63_insert-string/insert-string.js
> +  if (insertable === undefined) return str;
!insertable

2019-09-24 07:53 UTC, vovcyan commented on tasks/63_insert-string/insert-string.js
> +  str.substring(0, position) +
Make it in one line

2019-09-24 07:53 UTC, vovcyan commented on tasks/69_unpack-elements/unpack-elements.js
> +  let result = [];
const

2019-09-24 07:53 UTC, vovcyan commented on tasks/70_binary-decode/binary-decode.js
> +  return str === undefined ? '' :
!str

2019-09-24 07:53 UTC, vovcyan commented on tasks/70_binary-decode/binary-decode.js
> +  str
Please refactor it

2019-09-24 10:52 UTC, alexkond requested changes

2019-09-24 10:52 UTC, alexkond commented on tasks/65_smaller-common-multiple/smaller-common-multiple.js
> +function gcd(a, b) {
Try to avoid abbreviation if it's not common/conventional abbreviation. Don't try to save letters, code readability is more important.

2019-09-25 07:30 UTC, vovcyan requested changes

2019-09-25 07:30 UTC, vovcyan commented on tasks/63_insert-string/insert-string.js
> +  if (!insertable) return str;
if (!insertable) {
  return str;
}

2019-09-25 07:30 UTC, vovcyan commented on tasks/63_insert-string/insert-string.js
> +  return position === 0 ?
Please refactor this logic

2019-09-25 11:54 UTC, akimovaa approved these changes

2019-09-25 12:06 UTC, KalachevDev approved these changes

2019-09-25 12:10 UTC, merged