Timur katimullin tasks 71 80
linkouth/ui-internship-lwo2 pull request #8
Opened 2019-09-20 13:50 UTC by linkouth

Adds solutions 71-80 tasks.

2019-09-23 07:06 UTC, vovcyan requested changes

2019-09-23 07:06 UTC, vovcyan commented on tasks/71_binary-encode/binary-encode.js
> +  str
Please format it

2019-09-23 07:06 UTC, vovcyan commented on tasks/72_carrying/carrying.js
> +  const firstArg = args[0];
ES6

2019-09-23 07:06 UTC, vovcyan commented on tasks/73_check-for-palindromes/check-for-palindromes.js
> +    if (filteredString[i] !== filteredString[filteredString.length - i - 1]) {
Split it

2019-09-23 07:06 UTC, vovcyan commented on tasks/74_dna-pairing/dna-pairing.js
> +  let elements = str.split('');
const

2019-09-23 07:06 UTC, vovcyan commented on tasks/76_deep-object-clone/deep-object-clone.js
> +  let result = {};
const

2019-09-23 07:06 UTC, vovcyan commented on tasks/78_valid-braces/valid-braces.js
> +  let stack = [];
const

2019-09-24 06:13 UTC, linkouth commented on tasks/78_valid-braces/valid-braces.js
> +  let stack = [];
Fixed

2019-09-24 06:13 UTC, linkouth commented on tasks/76_deep-object-clone/deep-object-clone.js
> +  let result = {};
Fixed

2019-09-24 06:13 UTC, linkouth commented on tasks/74_dna-pairing/dna-pairing.js
> +  let elements = str.split('');
Fixed

2019-09-24 06:13 UTC, linkouth commented on tasks/73_check-for-palindromes/check-for-palindromes.js
> +    if (filteredString[i] !== filteredString[filteredString.length - i - 1]) {
Fixed

2019-09-24 06:13 UTC, linkouth commented on tasks/72_carrying/carrying.js
> +  const firstArg = args[0];
Fixed

2019-09-24 06:13 UTC, linkouth commented on tasks/71_binary-encode/binary-encode.js
> +  str
Fixed

2019-09-24 10:59 UTC, alexkond approved these changes

2019-09-25 07:31 UTC, vovcyan approved these changes

2019-09-25 07:31 UTC, merged