Timur katimullin 81 90 tasks
linkouth/ui-internship-lwo2 pull request #9
Opened 2019-09-21 13:50 UTC by linkouth

Adds 81-90 tasks solutions.

2019-09-23 07:04 UTC, vovcyan requested changes

2019-09-23 07:04 UTC, vovcyan commented on tasks/82_bouncing-balls/bouncing-balls.js
> +  let times = Math.floor(Math.log(window / h) / Math.log(bounce));
const

2019-09-23 07:04 UTC, vovcyan commented on tasks/86_working-hours/working-hours.js
> +    schedule[day.day.toUpperCase()] = day.from + ' - ' + day.to;
Split it

2019-09-23 07:04 UTC, vovcyan commented on tasks/86_working-hours/working-hours.js
> +  const result = [weekByDays[0]];
Use ES6 features

2019-09-23 07:04 UTC, vovcyan commented on tasks/86_working-hours/working-hours.js
> +      );
Move it to previous line

2019-09-25 11:54 UTC, akimovaa approved these changes

2019-09-25 12:07 UTC, KalachevDev approved these changes

2019-09-25 12:10 UTC, merged